const actionsTypes = {
  // Theme Actions START
  ON_DARK_MODE: "ON_DARK_MODE",
  OFF_DARK_MODE: "OFF_DARK_MODE",
  // Theme Actions END
  // Users Actions START
  //login
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  //logout
  USER_LOGIN_LOGOUT: "USER_LOGIN_LOGOUT",
  //register
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  //delete
  USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  USER_DELETE_FAIL: "USER_DELETE_FAIL",
  // Users Actions END
};

export default actionsTypes;
